service: moneybox-notifier

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 512

  stage: dev
  stackName: moneybox-notifier
  role: arn:aws:iam::530088275162:role/aws-sns-role

functions:
  notify:
    handler: handler.notify
    events:
      - schedule: cron(0 12 ? * MON *)